<?php

namespace AppBundle\Repository;

/**
 * CustomerTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerTableRepository extends \Doctrine\ORM\EntityRepository
{
}
