<?php

namespace AppBundle\Repository;

/**
 * OrderListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderListRepository extends \Doctrine\ORM\EntityRepository
{
}
